item {
  id: 1
  name: 'dokuz'
}

item {
  id: 2
  name: 'on'
}

item {
  id: 3
  name: 'vale'
}

item {
  id: 4
  name: 'kiz'
}

item {
  id: 5
  name: 'papaz'
}

item {
  id: 6
  name: 'as'
}